name: Diff

on:
  pull_request:

jobs:
  diff:
    name: Diff
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Diff stable
        run: |
            make CHANNEL=stable diff

      - name: Diff test
        run: |
            make CHANNEL=test diff

